### ISSUE TITLE
Help: I am looking for free Finnish language dialog Corpus.

### ISSUE THREAD

**Issue by remotejob** [mikahama/python-korp#3]
I am looking for free Finnish language dialog Corpus. I am private person.
I need create Finnish speaking bot.
Any help appreciated.
Kiitos. 

Yours page on https://mikakalevi.com/
"Send me a message" don't work.

**Comment by mikahama** [comment]
How about Opusparcus https://korp.csc.fi/download/opusparcus/ it has subtitles. Check out Opus corpus for more corpora http://opus.nlpl.eu/ .
Btw. Thanks for informing me about the issue on my page, I fixed it now
